// <auto-generated>
//     이 파일은 DefinitionEnumGenerator가 생성했습니다. 직접 수정하지 마세요.
//     원본: EntityDefinition 에셋 (DefinitionDatabase에 등록된 것)
//     수정하려면 정의 에셋을 고친 뒤 메뉴 [XNP/정의/enum 재생성]을 실행하세요.
// </auto-generated>

/// <summary>
/// 맵에 배치되는 개체(식생물·건물·바닥 프리팹) 식별자.
///
/// 정수값 = MapEntity.id / StampElement.id의 raw int 값과 같습니다.
/// </summary>
public enum EntityType
{
    /// <summary>없음</summary>
    None = 0,

    /// <summary>독성 고사리</summary>
    ToxicFern = 20,

    /// <summary>부패한 버섯</summary>
    CorruptedMushroom = 21,

    /// <summary>나무</summary>
    Tree2x3 = 2001,

    /// <summary>채용 사무소</summary>
    HiringOffice = 2002,

    /// <summary>베리 덤불</summary>
    BerryBush = 2003,

    /// <summary>나무 사다리</summary>
    WoodLadder = 2004,

    /// <summary>상자</summary>
    Chest = 2005,

    /// <summary>나무 문</summary>
    WoodDoor = 2006,

    /// <summary>나무 바닥</summary>
    WoodFloor = 2010,

    /// <summary>돌 바닥</summary>
    StoneFloor = 2011,

    /// <summary>금속 바닥</summary>
    MetalFloor = 2012,

    /// <summary>흙 바닥</summary>
    DirtFloor = 2013,

    /// <summary>구리 바닥</summary>
    CopperFloor = 2014,

    /// <summary>금 바닥</summary>
    GoldFloor = 2015,

    /// <summary>은 바닥</summary>
    SilverFloor = 2016,
}
