// <auto-generated>
//     이 파일은 DefinitionEnumGenerator가 생성했습니다. 직접 수정하지 마세요.
//     원본: FloorTileDefinition 에셋 (DefinitionDatabase에 등록된 것)
//     수정하려면 정의 에셋을 고친 뒤 메뉴 [XNP/정의/enum 재생성]을 실행하세요.
// </auto-generated>

/// <summary>
/// 건설되는 바닥 타일 종류 식별자.
///
/// 정수값 = FloorTile 프리팹에 직렬화된 값과 같습니다.
/// </summary>
public enum FloorTileType
{
    /// <summary>나무 바닥</summary>
    WoodFloor = 0,

    /// <summary>돌 바닥</summary>
    StoneFloor = 1,

    /// <summary>금속 바닥</summary>
    MetalFloor = 2,

    /// <summary>나무 사다리</summary>
    WoodLadder = 3,

    /// <summary>금속 사다리</summary>
    MetalLadder = 4,

    /// <summary>좁은 통로</summary>
    Catwalk = 5,

    /// <summary>다리</summary>
    Bridge = 6,

    /// <summary>가공된 흙 바닥</summary>
    DirtFloor = 7,
}
