// <auto-generated>
//     이 파일은 DefinitionEnumGenerator가 생성했습니다. 직접 수정하지 마세요.
//     원본: TileDefinition 에셋 (DefinitionDatabase에 등록된 것)
//     수정하려면 정의 에셋을 고친 뒤 메뉴 [XNP/정의/enum 재생성]을 실행하세요.
// </auto-generated>

/// <summary>
/// 블록(지형 타일) 종류 식별자.
///
/// 정수값 = GameMap.TileGrid의 raw int 값과 같습니다.
/// </summary>
public enum TileType
{
    /// <summary>빈 공간</summary>
    Air = 0,

    /// <summary>흙</summary>
    Dirt = 1,

    /// <summary>돌</summary>
    Stone = 2,

    /// <summary>구리 광석</summary>
    CopperOre = 3,

    /// <summary>철 광석</summary>
    IronOre = 4,

    /// <summary>금 광석</summary>
    GoldOre = 5,

    /// <summary>잔디흙</summary>
    GrassDirt = 6,

    /// <summary>가공된 흙</summary>
    ProcessedDirt = 7,

    /// <summary>사다리</summary>
    Ladder = 8,

    /// <summary>석탄</summary>
    Coal = 9,

    /// <summary>은 광석</summary>
    SilverOre = 10,

    /// <summary>수정</summary>
    Crystal = 11,

    /// <summary>덩굴 줄기 — 최하층에 얽혀 있는 굵은 뿌리. 침식을 뿜으며, 열매가 여기서 자란다.</summary>
    Trunk = 12,

    /// <summary>특수</summary>
    Special = 99,
}
